version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RAILWAY_ENVIRONMENT=development
    volumes:
      - ./data:/app/data
      - ./app/static/uploads:/app/app/static/uploads
      - ./temp:/app/temp
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Add database service for future expansion
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: checkmate_virtue
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data: 