version: '3.8'

services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexicon_app
    ports:
      - "8000:8000"
    environment:
      - APP_BASE_URL=http://localhost:8000
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./temp:/app/temp
      - ./artifacts:/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
